// Generated by https://quicktype.io

export interface IAuthResponse {
  data:  IUserData;
  token: string;
}

export interface IUserData {
  fullname: string;
  email:    string;
  phone:    null;
  google:   boolean;
  isVerify: boolean;
  createAt: string;
  status:   boolean;
  roles:    Role[];
  country:  Country;
}

export interface Country {
  id:            string;
  name:          string;
  timeZone:      string;
  isoAlphaThree: string;
  moneyCode:     string;
  moneySymbol:   string;
  prefixPhone:   string;
  img:           string;
}

export interface Role {
  id:   string;
  name: string;
  code: string;
}
